# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Solution for problem 1
#' @param x An atomic vector
#' @export
sol1_C <- function(x) {
    .Call('euleR_sol1_C', PACKAGE = 'euleR', x)
}

#' Solution for problem 1
#' @param x An atomic vector
#' @export
sol2_C <- function(input) {
    .Call('euleR_sol2_C', PACKAGE = 'euleR', input)
}

